begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
set local statement_timeout='15s';set local lock_timeout='3s';set local idle_in_transaction_session_timeout='30s';
select no_plan();
insert into public.users(id,email,display_name) values ('a7777777-7777-4777-8777-777777777771','room-v2-free@example.test','Free'),('a7777777-7777-4777-8777-777777777772','room-v2-pro@example.test','Pro');
insert into public.account_manual_plan_grants(user_id,plan_code,valid_until,reason)values('a7777777-7777-4777-8777-777777777772','pro',clock_timestamp()+interval '10 minutes','Task7 synthetic');
create function pg_temp.create_room_v2(owner_id uuid,request_id text,version integer default 2)returns jsonb language plpgsql as $$
declare result jsonb;
begin
 if version=1 then
 select room_record into result from public.create_room_with_active_session_v1(owner_id,'task7-session',null,null,null,null,null,null,null,request_id,'free',4,4,false,false);
 else
 select room_record into result from public.create_room_with_active_session_v2(owner_id,'task7-session',null,null,null,null,null,null,null,request_id,'free',4,4,false,false,2);
 end if;return result;
end $$;
create temporary table task7_result(name text primary key,value jsonb);
insert into task7_result values('legacy',pg_temp.create_room_v2('a7777777-7777-4777-8777-777777777771','legacy',1));
select ok((select value->'media_lease'='null'::jsonb from task7_result where name='legacy'),'inactive policy creates legacy room');
update public.personal_history_policy set active=true where singleton;
select lives_ok($$select public.claim_active_room_session_v1('a7777777-7777-4777-8777-777777777771',(select value->>'room_id' from task7_result where name='legacy'),'host','task7-session')$$,'existing legacy room reconnects under active policy');
select lives_ok($$select public.claim_active_room_session_v2('a7777777-7777-4777-8777-777777777771',(select value->>'room_id' from task7_result where name='legacy'),'host','task7-session',2)$$,'new negotiated client also reconnects to unchanged legacy room');
update public.personal_history_policy set active=false where singleton;
select * from public.finalize_room_usage((select value->>'room_id' from task7_result where name='legacy'),clock_timestamp(),current_date,0);
update public.personal_history_policy set active=true where singleton;
select throws_ok($$select pg_temp.create_room_v2('a7777777-7777-4777-8777-777777777771','blocked',1)$$,'P0001','ROOM_UPDATE_REQUIRED','active policy rejects old Web create RPC');
insert into task7_result values('free',pg_temp.create_room_v2('a7777777-7777-4777-8777-777777777771','free-v2'));
insert into task7_result values('pro',pg_temp.create_room_v2('a7777777-7777-4777-8777-777777777772','pro-v2'));
select throws_ok($$select public.claim_active_room_session_v1('a7777777-7777-4777-8777-777777777771',(select value->>'room_id' from task7_result where name='free'),'host','old-web-session')$$,'P0001','ROOM_UPDATE_REQUIRED','oldWeb cannot mint legacy token for existing v2 room');
select is((select value#>>'{media_lease,capabilities,maxParticipants}' from task7_result where name='pro'),'15','durable Pro overrides caller Free');
select is((select value#>>'{media_lease,capabilities,maxMicrophones}' from task7_result where name='pro'),'8','Pro has independent8microphones');
select ok((select (value#>>'{media_lease,capabilities,capabilitiesValidUntil}')::timestamptz <= (value#>>'{media_lease,paidUntil}')::timestamptz from task7_result where name='pro'),'lease capped at selected-plan expiry');
update public.rooms set created_at=clock_timestamp()-interval '1 day' where room_id=(select value->>'room_id' from task7_result where name='free');
select is(public.commit_room_usage_day_v1((select value->>'room_id' from task7_result where name='free'),current_date-1,120)->>'seconds','120','closed day120seconds ACK');
select is((select status from public.rooms where room_id=(select value->>'room_id' from task7_result where name='free')),'lobby','nonterminal day commit does not end room');
select is(public.commit_room_usage_day_v1((select value->>'room_id' from task7_result where name='free'),current_date,180)->>'seconds','180','current day180seconds ACK');
select is(public.commit_room_usage_day_v1((select value->>'room_id' from task7_result where name='free'),current_date-1,120)->>'seconds','120','repeated cumulative ACK is idempotent');
select is(public.commit_room_usage_day_v1((select value->>'room_id' from task7_result where name='free'),current_date-1,90)->>'seconds','120','older cumulative retry does not decrement');
select is((select host_seconds from public.usage_daily where user_id='a7777777-7777-4777-8777-777777777771' and day=current_date-1),120,'exact day1total120');
select * from public.finalize_room_usage((select value->>'room_id' from task7_result where name='free'),clock_timestamp(),current_date,180);
select * from public.finalize_room_usage((select value->>'room_id' from task7_result where name='free'),clock_timestamp(),current_date,180);
select is((select host_seconds from public.usage_daily where user_id='a7777777-7777-4777-8777-777777777771' and day=current_date),180,'double finalization leaves exact day2total180');
select throws_ok($$select public.commit_room_usage_day_v1((select value->>'room_id' from task7_result where name='pro'),current_date,100)$$,'P0001','ROOM_USAGE_NOT_METERED','paid room time never charged');
update public.account_manual_plan_grants set plan_code='plus' where user_id='a7777777-7777-4777-8777-777777777772';
insert into task7_result values('denied',public.renew_room_media_lease_v2((select value->>'room_id' from task7_result where name='pro')));
select is((select value->>'denied' from task7_result where name='denied'),'true','Pro room authority lost even if Plus history remains');
select is((public.resolve_watch_history_access_v1('a7777777-7777-4777-8777-777777777772')#>>'{history,state}'),'allowed','Plus still retains history');
select is(public.renew_room_media_lease_v2((select value->>'room_id' from task7_result where name='pro'))->>'closingAt',(select value->>'closingAt' from task7_result where name='denied'),'repeated renewal never resets close deadline');
select ok(not has_function_privilege('anon','public.commit_room_usage_day_v1(text,date,integer)','EXECUTE'),'anon cannot charge quota');
select ok(not has_function_privilege('authenticated','public.renew_room_media_lease_v2(text)','EXECUTE'),'browser cannot renew authority');
select ok(not has_function_privilege('service_role','anidachi_room_private.create_room_with_active_session_v1(uuid,text,text,text,text,text,text,bigint,text,text,text,integer,integer,boolean,boolean)','EXECUTE'),'server cannot bypass legacy/create fence directly');
select throws_ok($$select public.claim_active_room_session_v2('a7777777-7777-4777-8777-777777777772',(select value->>'room_id' from task7_result where name='pro'),'host','mismatch-session',1)$$,'P0001','ROOM_UPDATE_REQUIRED','negotiated mismatch cannot mutate assignment');
select lives_ok($$select public.claim_active_room_session_v2('a7777777-7777-4777-8777-777777777772',(select value->>'room_id' from task7_result where name='pro'),'host','valid-v2-session',2)$$,'negotiated v2 claim succeeds');
select ok((select relrowsecurity from pg_class where oid='public.room_usage_days_v1'::regclass),'ledger RLS enabled');
select ok((select bool_and(p.prosecdef and p.proconfig @> array['search_path=""']::text[] and has_function_privilege('service_role',p.oid,'EXECUTE') and not has_function_privilege('public',p.oid,'EXECUTE') and not has_function_privilege('anon',p.oid,'EXECUTE') and not has_function_privilege('authenticated',p.oid,'EXECUTE')) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('create_room_with_active_session_v1','create_room_with_active_session_v2','claim_active_room_session_v1','claim_active_room_session_v2')), 'all admission wrappers are safe definer functions with service-only execute allowlist');
select ok((select bool_and(not has_function_privilege('service_role',p.oid,'EXECUTE') and not has_function_privilege('public',p.oid,'EXECUTE') and not has_function_privilege('anon',p.oid,'EXECUTE') and not has_function_privilege('authenticated',p.oid,'EXECUTE')) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='anidachi_room_private'), 'all private admission cores deny direct browser and service execution');
select throws_ok($$select public.commit_room_usage_day_v1((select value->>'room_id' from task7_result where name='free'),current_date+1,1)$$,'22023','ROOM_USAGE_INVALID','nonzero future-day usage still rejected');
select * from finish();
rollback;
