"""Repository Graphify update: resolved raw AST, lossless historical storage.

Semantic fragments must be produced by the Codex Graphify skill and include
source_hashes. This script never invokes an LLM or reads provider credentials.
"""
import argparse
from copy import deepcopy
import hashlib
import json
import os
from pathlib import Path
import tempfile

import networkx as nx
from graphify.build import mint_external_stubs_in_data
from graphify.detect import detect_incremental, save_manifest
from graphify.extract import extract
from graphify.cluster import score_all
from graphify.analyze import god_nodes, surprising_connections, suggest_questions
from graphify.report import generate

from graphify_safe_merge import merge_graph, tier


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def relative(root, path):
    return Path(path).resolve().relative_to(root).as_posix()


def read_json(path, default):
    return json.loads(path.read_text()) if path.exists() else default


def render_report(graph, root, detection):
    # Analysis projection only. Never serialize this simple graph over the raw
    # graph: its parallel relationships are deliberately retained in graph.json.
    graph = deepcopy(graph)
    g = nx.Graph()
    by_source = {}
    next_id = max((n.get("community", -1) for n in graph["nodes"]), default=-1) + 1
    for n in graph["nodes"]:
        if "community" in n:
            by_source.setdefault(n.get("source_file"), n["community"])
    for n in graph["nodes"]:
        if "community" not in n:
            sf = n.get("source_file")
            if sf not in by_source:
                by_source[sf] = next_id
                next_id += 1
            n["community"] = by_source[sf]
        g.add_node(n["id"], **{k: v for k, v in n.items() if k != "id"})
    for e in graph["links"]:
        g.add_edge(e["source"], e["target"], **e)
    communities, labels = {}, {}
    for n in graph["nodes"]:
        cid = n["community"]
        communities.setdefault(cid, []).append(n["id"])
        labels.setdefault(cid, n.get("community_name") or n.get("source_file") or "External dependencies")
    for n in graph["nodes"]:
        n.setdefault("community_name", labels[n["community"]])
    report = generate(g, communities, score_all(g, communities), labels,
                      god_nodes(g), surprising_connections(g, communities),
                      {**detection, "total_files": len(by_source)}, {"input": 0, "output": 0},
                      str(root), suggested_questions=suggest_questions(g, communities, labels))
    report = report.replace("- Token cost: 0 input · 0 output", "- Token cost: AST uses no LLM; Codex semantic usage unavailable")
    return ("<!-- Generated by scripts/graphify_update.py. -->\n"
            "Stored graph preserves directed endpoints, parallel facts and existing community IDs.\n"
            f"Stored records: {len(graph['nodes'])} nodes, {len(graph['links'])} links, "
            f"{len(graph.get('hyperedges', []))} hyperedges. "
            "Analysis below uses an undirected simple projection; communities are retained, not reclustered.\n"
            "AST uses no LLM. Codex semantic token usage is unavailable.\n\n" + report)


def update(root, semantic_path=None, ast_sources_path=None):
    out = root / "graphify-out"
    out.mkdir(exist_ok=True)
    paths = [out / name for name in ("graph.json", "manifest.json", "GRAPH_REPORT.md")]
    originals = {p: p.read_bytes() if p.exists() else None for p in paths}
    base = read_json(paths[0], {"nodes": [], "links": [], "directed": False, "multigraph": False})
    detection = detect_incremental(root, kind="ast")
    code_paths = [Path(p) for p in detection["new_files"].get("code", [])]
    if ast_sources_path:
        # Explicit repair/re-extraction scope; never fake or erase manifest rows.
        allowed = {relative(root, p) for p in detection["files"].get("code", [])}
        requested = {relative(root, root / p) for p in read_json(ast_sources_path, [])}
        if requested - allowed:
            raise ValueError("Requested AST source is outside the detected code corpus")
        code_paths = sorted(set(code_paths) | {root / p for p in requested})
    ast_sources = {relative(root, p) for p in code_paths}
    deleted = {relative(root, p) for p in detection.get("deleted_files", [])}
    snapshots = {relative(root, p): p.read_bytes() for p in code_paths}
    hashes = {source: hashlib.sha256(data).hexdigest() for source, data in snapshots.items()}
    fresh = {"nodes": [], "edges": [], "hyperedges": []}
    semantic_sources = set()
    if semantic_path:
        semantic = read_json(semantic_path, {})
        supplied = semantic.get("source_hashes", {})
        if not supplied:
            raise ValueError("Semantic fragment must include source_hashes")
        for source, expected in supplied.items():
            path = (root / source).resolve()
            source = relative(root, path)
            data = path.read_bytes()
            if hashlib.sha256(data).hexdigest() != expected:
                raise ValueError(f"Stale semantic fragment: {source}")
            semantic_sources.add(source)
            hashes[source] = expected
            snapshots[source] = data
        for key in fresh:
            for original in semantic.get(key, []):
                item = dict(original)
                item["source_file"] = relative(root, root / item["source_file"])
                item["_origin"] = "semantic"
                fresh[key].append(item)
    if not ast_sources and not semantic_sources and not deleted:
        print("Graphify: no code changes; graph, report and manifest unchanged.")
        return
    if code_paths:
        context = [n for n in base["nodes"] if tier(n) == "ast"]
        ast = extract(code_paths, cache_root=root, root=root,
                      resolution_context_nodes=context)
        if ast.get("failed_files") or ast.get("failed_sources"):
            raise ValueError("AST extraction incomplete; existing graph preserved")
        # extract() resolves cross-file imports itself. Keep its raw records:
        # even a fresh DiGraph collapses parallel relations/provenance.
        known = {n["id"] for n in base["nodes"]}
        declared = {n["id"] for n in ast["nodes"]}
        stubs = {"nodes": ast["nodes"] + [{"id": id} for id in known - declared],
                 "edges": ast["edges"]}
        start = len(stubs["nodes"])
        mint_external_stubs_in_data(stubs)
        for attrs in ast["nodes"] + stubs["nodes"][start:]:
            id = attrs["id"]
            sf = attrs.get("source_file")
            if sf and sf not in ast_sources:
                if id in known:
                    continue
                raise ValueError(f"Unresolved cross-source AST node: {id} ({sf})")
            fresh["nodes"].append({"id": id, **attrs, "_origin": "ast"})
        fresh["edges"].extend({**e, "_origin": "ast"} for e in ast["edges"])
    candidate = merge_graph(base, fresh, ast_sources, semantic_sources, deleted=deleted)
    report = render_report(candidate, root, detection)
    # Recheck sources and all three artifacts before committing a bundle.
    for source, expected in hashes.items():
        if digest(root / source) != expected:
            raise ValueError(f"Source changed during extraction: {source}")
    with tempfile.TemporaryDirectory(prefix=".update-", dir=out) as tmp:
        tmp = Path(tmp)
        manifest = tmp / "manifest.json"
        if originals[paths[1]] is not None:
            manifest.write_bytes(originals[paths[1]])
        if code_paths:
            save_manifest({"code": [str(p) for p in code_paths]}, str(manifest), kind="ast", root=root)
        if semantic_sources:
            save_manifest({"document": [str(root / s) for s in sorted(semantic_sources)]},
                          str(manifest), kind="semantic", root=root)
        if deleted:
            data = read_json(manifest, {})
            for source in deleted:
                data.pop(source, None)
            manifest.write_text(json.dumps(data, indent=2) + "\n")
        if not manifest.exists():
            manifest.write_text("{}\n")
        staged_manifest = read_json(manifest, {})
        for kind, sources in (("ast", ast_sources), ("semantic", semantic_sources)):
            for source in sources:
                expected = hashlib.md5(snapshots[source]).hexdigest()
                if staged_manifest.get(source, {}).get(kind + "_hash") != expected:
                    raise ValueError(f"Source hash changed during manifest staging: {source}")
        (tmp / "graph.json").write_text(json.dumps(candidate, indent=2, ensure_ascii=False) + "\n")
        (tmp / "GRAPH_REPORT.md").write_text(report)
        for p in paths:
            current = p.read_bytes() if p.exists() else None
            if current != originals[p]:
                raise ValueError(f"Concurrent graph change: {p.name}")
        for source, expected in hashes.items():
            if digest(root / source) != expected:
                raise ValueError(f"Source changed before graph publication: {source}")
        # Keep a recoverable bundle even if the process is interrupted mid-write.
        backup = Path(tempfile.mkdtemp(prefix=".backup-", dir=out))
        for p, contents in originals.items():
            if contents is not None:
                (backup / p.name).write_bytes(contents)
        replaced = []
        try:
            for p in paths:
                os.replace(tmp / p.name, p)
                replaced.append(p)
        except BaseException:
            for p in replaced:
                if originals[p] is None:
                    p.unlink(missing_ok=True)
                else:
                    p.write_bytes(originals[p])
            raise
    print(f"Graphify: updated {len(ast_sources)} AST and {len(semantic_sources)} semantic sources; "
          f"{len(candidate['nodes'])} nodes, {len(candidate['links'])} links. Backup: {backup.name}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--semantic", type=Path)
    parser.add_argument("--ast-sources", type=Path, help="JSON list of detected code paths to re-extract")
    args = parser.parse_args()
    root = Path.cwd().resolve()
    lock = root / "graphify-out" / ".update.lock"
    lock.parent.mkdir(exist_ok=True)
    with lock.open("a") as handle:
        # Supported developer hosts are macOS/Linux. Serializes competing updates.
        import fcntl
        fcntl.flock(handle, fcntl.LOCK_EX)
        update(root, args.semantic, args.ast_sources)
